version: '3.2'

services:
  fpm:
    build: ./docker/php
    image: php:7.4-fpm
    networks:
      - app-network
    tty: true
    ports:
      - "${FPM_PORT:-9000}:9000"
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
  nginx:
    image: nginx:latest
    depends_on:
      - fpm
    networks:
      - app-network
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx

networks:
  app-network:
    driver: bridge